/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedLayoutRouteRouteImport } from './routes/_authedLayout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthedLayoutSignupRequestsIndexRouteImport } from './routes/_authedLayout/signup-requests/index'
import { Route as AuthedLayoutMembersIndexRouteImport } from './routes/_authedLayout/members/index'
import { Route as AuthedLayoutDashboardIndexRouteImport } from './routes/_authedLayout/dashboard/index'
import { Route as AuthedLayoutSignupRequestsRequestsIdIndexRouteImport } from './routes/_authedLayout/signup-requests/$requestsId/index'
import { Route as AuthedLayoutMembersMemberIdIndexRouteImport } from './routes/_authedLayout/members/$memberId/index'
import { Route as AuthedLayoutSignupRequestsRequestsIdCheckInfoIndexRouteImport } from './routes/_authedLayout/signup-requests/$requestsId/check-Info/index'

const AuthedLayoutRouteRoute = AuthedLayoutRouteRouteImport.update({
  id: '/_authedLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedLayoutSignupRequestsIndexRoute =
  AuthedLayoutSignupRequestsIndexRouteImport.update({
    id: '/signup-requests/',
    path: '/signup-requests/',
    getParentRoute: () => AuthedLayoutRouteRoute,
  } as any)
const AuthedLayoutMembersIndexRoute =
  AuthedLayoutMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AuthedLayoutRouteRoute,
  } as any)
const AuthedLayoutDashboardIndexRoute =
  AuthedLayoutDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthedLayoutRouteRoute,
  } as any)
const AuthedLayoutSignupRequestsRequestsIdIndexRoute =
  AuthedLayoutSignupRequestsRequestsIdIndexRouteImport.update({
    id: '/signup-requests/$requestsId/',
    path: '/signup-requests/$requestsId/',
    getParentRoute: () => AuthedLayoutRouteRoute,
  } as any)
const AuthedLayoutMembersMemberIdIndexRoute =
  AuthedLayoutMembersMemberIdIndexRouteImport.update({
    id: '/members/$memberId/',
    path: '/members/$memberId/',
    getParentRoute: () => AuthedLayoutRouteRoute,
  } as any)
const AuthedLayoutSignupRequestsRequestsIdCheckInfoIndexRoute =
  AuthedLayoutSignupRequestsRequestsIdCheckInfoIndexRouteImport.update({
    id: '/signup-requests/$requestsId/check-Info/',
    path: '/signup-requests/$requestsId/check-Info/',
    getParentRoute: () => AuthedLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login/': typeof LoginIndexRoute
  '/dashboard/': typeof AuthedLayoutDashboardIndexRoute
  '/members/': typeof AuthedLayoutMembersIndexRoute
  '/signup-requests/': typeof AuthedLayoutSignupRequestsIndexRoute
  '/members/$memberId/': typeof AuthedLayoutMembersMemberIdIndexRoute
  '/signup-requests/$requestsId/': typeof AuthedLayoutSignupRequestsRequestsIdIndexRoute
  '/signup-requests/$requestsId/check-Info/': typeof AuthedLayoutSignupRequestsRequestsIdCheckInfoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/dashboard': typeof AuthedLayoutDashboardIndexRoute
  '/members': typeof AuthedLayoutMembersIndexRoute
  '/signup-requests': typeof AuthedLayoutSignupRequestsIndexRoute
  '/members/$memberId': typeof AuthedLayoutMembersMemberIdIndexRoute
  '/signup-requests/$requestsId': typeof AuthedLayoutSignupRequestsRequestsIdIndexRoute
  '/signup-requests/$requestsId/check-Info': typeof AuthedLayoutSignupRequestsRequestsIdCheckInfoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authedLayout': typeof AuthedLayoutRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/_authedLayout/dashboard/': typeof AuthedLayoutDashboardIndexRoute
  '/_authedLayout/members/': typeof AuthedLayoutMembersIndexRoute
  '/_authedLayout/signup-requests/': typeof AuthedLayoutSignupRequestsIndexRoute
  '/_authedLayout/members/$memberId/': typeof AuthedLayoutMembersMemberIdIndexRoute
  '/_authedLayout/signup-requests/$requestsId/': typeof AuthedLayoutSignupRequestsRequestsIdIndexRoute
  '/_authedLayout/signup-requests/$requestsId/check-Info/': typeof AuthedLayoutSignupRequestsRequestsIdCheckInfoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/dashboard/'
    | '/members/'
    | '/signup-requests/'
    | '/members/$memberId/'
    | '/signup-requests/$requestsId/'
    | '/signup-requests/$requestsId/check-Info/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/members'
    | '/signup-requests'
    | '/members/$memberId'
    | '/signup-requests/$requestsId'
    | '/signup-requests/$requestsId/check-Info'
  id:
    | '__root__'
    | '/'
    | '/_authedLayout'
    | '/login/'
    | '/_authedLayout/dashboard/'
    | '/_authedLayout/members/'
    | '/_authedLayout/signup-requests/'
    | '/_authedLayout/members/$memberId/'
    | '/_authedLayout/signup-requests/$requestsId/'
    | '/_authedLayout/signup-requests/$requestsId/check-Info/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedLayoutRouteRoute: typeof AuthedLayoutRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authedLayout': {
      id: '/_authedLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authedLayout/signup-requests/': {
      id: '/_authedLayout/signup-requests/'
      path: '/signup-requests'
      fullPath: '/signup-requests/'
      preLoaderRoute: typeof AuthedLayoutSignupRequestsIndexRouteImport
      parentRoute: typeof AuthedLayoutRouteRoute
    }
    '/_authedLayout/members/': {
      id: '/_authedLayout/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof AuthedLayoutMembersIndexRouteImport
      parentRoute: typeof AuthedLayoutRouteRoute
    }
    '/_authedLayout/dashboard/': {
      id: '/_authedLayout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedLayoutDashboardIndexRouteImport
      parentRoute: typeof AuthedLayoutRouteRoute
    }
    '/_authedLayout/signup-requests/$requestsId/': {
      id: '/_authedLayout/signup-requests/$requestsId/'
      path: '/signup-requests/$requestsId'
      fullPath: '/signup-requests/$requestsId/'
      preLoaderRoute: typeof AuthedLayoutSignupRequestsRequestsIdIndexRouteImport
      parentRoute: typeof AuthedLayoutRouteRoute
    }
    '/_authedLayout/members/$memberId/': {
      id: '/_authedLayout/members/$memberId/'
      path: '/members/$memberId'
      fullPath: '/members/$memberId/'
      preLoaderRoute: typeof AuthedLayoutMembersMemberIdIndexRouteImport
      parentRoute: typeof AuthedLayoutRouteRoute
    }
    '/_authedLayout/signup-requests/$requestsId/check-Info/': {
      id: '/_authedLayout/signup-requests/$requestsId/check-Info/'
      path: '/signup-requests/$requestsId/check-Info'
      fullPath: '/signup-requests/$requestsId/check-Info/'
      preLoaderRoute: typeof AuthedLayoutSignupRequestsRequestsIdCheckInfoIndexRouteImport
      parentRoute: typeof AuthedLayoutRouteRoute
    }
  }
}

interface AuthedLayoutRouteRouteChildren {
  AuthedLayoutDashboardIndexRoute: typeof AuthedLayoutDashboardIndexRoute
  AuthedLayoutMembersIndexRoute: typeof AuthedLayoutMembersIndexRoute
  AuthedLayoutSignupRequestsIndexRoute: typeof AuthedLayoutSignupRequestsIndexRoute
  AuthedLayoutMembersMemberIdIndexRoute: typeof AuthedLayoutMembersMemberIdIndexRoute
  AuthedLayoutSignupRequestsRequestsIdIndexRoute: typeof AuthedLayoutSignupRequestsRequestsIdIndexRoute
  AuthedLayoutSignupRequestsRequestsIdCheckInfoIndexRoute: typeof AuthedLayoutSignupRequestsRequestsIdCheckInfoIndexRoute
}

const AuthedLayoutRouteRouteChildren: AuthedLayoutRouteRouteChildren = {
  AuthedLayoutDashboardIndexRoute: AuthedLayoutDashboardIndexRoute,
  AuthedLayoutMembersIndexRoute: AuthedLayoutMembersIndexRoute,
  AuthedLayoutSignupRequestsIndexRoute: AuthedLayoutSignupRequestsIndexRoute,
  AuthedLayoutMembersMemberIdIndexRoute: AuthedLayoutMembersMemberIdIndexRoute,
  AuthedLayoutSignupRequestsRequestsIdIndexRoute:
    AuthedLayoutSignupRequestsRequestsIdIndexRoute,
  AuthedLayoutSignupRequestsRequestsIdCheckInfoIndexRoute:
    AuthedLayoutSignupRequestsRequestsIdCheckInfoIndexRoute,
}

const AuthedLayoutRouteRouteWithChildren =
  AuthedLayoutRouteRoute._addFileChildren(AuthedLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedLayoutRouteRoute: AuthedLayoutRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
